<?php
/**
 * @package   Mivhak Syntax Highlighter
 * @date      2016-06-21
 * @version   1.3.6
 * @author    Askupa Software <contact@askupasoftware.com>
 * @link      http://products.askupasoftware.com/mivhak
 * @copyright 2016 Askupa Software
 */

/**
 * The following is a list of all supported programming languages
 */
return array(
    'abap'              => 'ABAP',
    'abc'               => 'ABC',
    'actionscript'      => 'ActionScript',
    'ada'               => 'Ada',
    'apache_conf'       => 'ApacheConf',
    'applescript'       => 'AppleScript',
    'asciidoc'          => 'AsciiDoc',
    'assembly_x86'      => 'Assembly x86',
    'autohotkey'        => 'AutoHotkey',
    'batchfile'         => 'Batch File',
    'c9search'          => 'c9search',
    'c_cpp'             => 'C/C++',
    'cirru'             => 'cirru',
    'clojure'           => 'Clojure',
    'cobol'             => 'COBOL',
    'coffee'            => 'CoffeeScript',
    'coldfusion'        => 'ColdFusion',
    'csharp'            => 'C#',
    'css'               => 'CSS',
    'curly'             => 'Curly',
    'd'                 => 'D',
    'dart'              => 'Dart',
    'diff'              => 'diff',
    'django'            => 'Django',
    'dockerfile'        => 'Dockerfile',
    'dot'               => 'DOT',
    'eiffel'            => 'Eiffel',
    'ejs'               => 'EJS',
    'elixir'            => 'Elixir',
    'elm'               => 'Elm',
    'erlang'            => 'Erlang',
    'forth'             => 'Forth',
    'ftl'               => 'FTL',
    'gcode'             => 'G-Code',
    'gherkin'           => 'Gherkin',
    'gitignore'         => 'gitignore',
    'glsl'              => 'GLSL',
    'gobstones'         => 'gobstones',
    'golang'            => 'Go',
    'groovy'            => 'Groovy',
    'haml'              => 'Haml',
    'handlebars'        => 'Handlebars',
    'haskell'           => 'Haskell',
    'haxe'              => 'Haxe',
    'html'              => 'HTML',
    'html_elixir'       => 'HTML Elixir',
    'html_ruby'         => 'HTML Ruby',
    'ini'               => 'INI',
    'io'                => 'io',
    'jack'              => 'JACK',
    'jade'              => 'Jade',
    'java'              => 'Java',
    'javascript'        => 'JavaScript',
    'json'              => 'JSON',
    'jsoniq'            => 'JSONiq',
    'jsp'               => 'JSP',
    'jsx'               => 'JSX',
    'julia'             => 'Julia',
    'latex'             => 'LaTex',
    'lean'              => 'Lean',
    'less'              => 'Less',
    'liquid'            => 'Liquid',
    'lisp'              => 'Lisp',
    'livescript'        => 'LiveScript',
    'logiql'            => 'LogiQL',
    'lsl'               => 'LSL',
    'lua'               => 'Lua',
    'luapage'           => 'Luapage',
    'lucene'            => 'Lucene',
    'makefile'          => 'Makefile',
    'markdown'          => 'Markdown',
    'mask'              => 'Mask',
    'matlab'            => 'MATLAB',
    'maze'              => 'Maze',
    'mel'               => 'MEL',
    'mipsassembler'     => 'MIPS Assembler',
    'mushcode'          => 'MUSHCode',
    'mysql'             => 'MySQL',
    'nix'               => 'nix',
    'nsis'              => 'NSIS',
    'objectivec'        => 'Objective-C',
    'ocaml'             => 'OCaml',
    'pascal'            => 'Pascal',
    'perl'              => 'Perl',
    'pgsql'             => 'pgSQL',
    'php'               => 'PHP',
    'plain_text'        => 'Plain Text',
    'powershell'        => 'PowerShell',
    'praat'             => 'Praat',
    'prolog'            => 'Prolog',
    'properties'        => 'Properties',
    'protobuf'          => 'Protocol Bufffers',
    'python'            => 'Python',
    'r'                 => 'R',
    'razor'             => 'Razor',
    'rdoc'              => 'RDoc',
    'rhtml'             => 'rhtml',
    'rst'               => 'reStructuredText',
    'ruby'              => 'Ruby',
    'rust'              => 'Rust',
    'sass'              => 'Sass',
    'scad'              => 'SCAD',
    'scala'             => 'Scala',
    'scheme'            => 'Scheme',
    'scss'              => 'SCSS',
    'sh'                => 'sh',
    'sjs'               => 'SJS',
    'smarty'            => 'Smarty',
    'snippets'          => 'Snippets',
    'soy_template'      => 'Soy Template',
    'space'             => 'Space',
    'sql'               => 'SQL',
    'sqlserver'         => 'SQLServer',
    'stylus'            => 'Stylus',
    'svg'               => 'SVG',
    'swift'             => 'Swift',
    'swig'              => 'Swig',
    'tcl'               => 'Tcl',
    'tex'               => 'Tex',
    'text'              => 'Text',
    'textile'           => 'Textile',
    'toml'              => 'Toml',
    'twig'              => 'Twig',
    'typescript'        => 'TypeScript',
    'vala'              => 'Vala',
    'vbscript'          => 'VBScript',
    'velocity'          => 'Velocity',
    'verilog'           => 'Verilog',
    'vhdl'              => 'VHDL',
    'wollok'            => 'Wollok',
    'xml'               => 'XML',
    'xquery'            => 'XQuery',
    'yaml'              => 'YAML'
);
